name: Build Application

on: push

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Execute Maven build
        run: ./mvnw package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build tagged Docker image
        run: docker build . -t miragon/camunda-7-plain:${{ env.RELEASE_VERSION }}
      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: miragon/camunda-7-plain:${{ env.RELEASE_VERSION }}
          fail-build: false
          debug: false
          acs-report-enable: true #GitHub Automated Code Scanning (ACS)
      - name: Parse SARIF file
        uses: FlowSquad/sarif-report-parse@v1.0.2
        with:
          sarif-file: ${{ steps.scan.outputs.sarif }}
