name: Build And Publish Application

on:
  workflow_dispatch:
    inputs:
      release-docker-image:
        description: 'Release Docker Image using version specified in pom.xml (y/n)?'
        required: true
        default: 'y'

jobs:
  build-and-publish-docker-image:
    if: github.event.inputs.release-docker-image == 'y'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Execute Maven build
        run: ./mvnw package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_MIRAGON_USERNAME }}
          password: ${{ secrets.DOCKER_MIRAGON_PASSWORD }}
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build and push camunda-7-plain
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: miragon/camunda-7-plain:${{ env.RELEASE_VERSION }},miragon/camunda-7-plain:latest
          platforms: linux/amd64, linux/arm64/v8
